sudo: required

services:
  - docker

script:
  - docker build -t thesis -f Dockerfile .
  - docker run --rm thesis /bin/bash -c "python -m pytest -sv --cov=. --cov-config=.coveragerc tests/ && coveralls"
